#
# This playbook installs tools a developer need to work on Ledger products
#

---
- hosts: localhost
  gather_facts: no
  connection: local

  vars:
    vscode_extensions:
      - {
          name: "Markdown Preview Enhanced",
          id: "shd101wyy.markdown-preview-enhanced",
        }
      - { name: "ESLint", id: "dbaeumer.vscode-eslint" }
      - { name: "Prettier - Code formatter", id: "esbenp.prettier-vscode" }
      - { name: "Live Share", id: "MS-vsliveshare.vsliveshare" }

    proto_tools:
      - { name: "node", version: "22.13.1" }
      - { name: "pnpm", version: "9.12.3" }
      - { name: "npm", version: "10.5.2" }

  vars_prompt:
    - name: zsh
      prompt: "Install Oh-my-zsh/Antigen?"
      default: "yes"
      private: no
    - name: sublime
      prompt: "Install Sublime Merge?"
      default: "yes"
      private: no
    - name: vscode
      prompt: "Install VSCode?"
      default: "yes"
      private: no
    - name: cursor
      prompt: "Install Cursor?"
      default: "yes"
      private: no
    - name: androidStudio
      prompt: "Install Android Studio?"
      default: "yes"
      private: no
    - name: password
      prompt: What is your admin password for sudo installs?

  tasks:
    - name: "Install Oh-my-zsh/Antigen"
      when: zsh|bool
      ansible.builtin.shell:
        cmd: curl -L git.io/antigen > ~/antigen.zsh

    - name: "Copy .zsh-ledger-dx file"
      when: zsh|bool
      template:
        src: files/zsh/.zsh-ledger-dx
        dest: ~/.zsh-ledger-dx

    - name: "Load .zsh-ledger-dx file in .zshrc"
      when: zsh|bool
      ansible.builtin.lineinfile:
        path: ~/.zshrc
        line: source ~/.zsh-ledger-dx
        create: true

    - name: "Install Sublime Merge"
      when: sublime|bool
      community.general.homebrew_cask:
        name: "{{ item }}"
      with_items:
        - sublime-merge

    - name: Check if VSCode app already exists
      when: vscode|bool
      ansible.builtin.stat:
        path: /Applications/Visual Studio Code.app
      register: vscode_app

    - name: "Install VSCode"
      when: vscode|bool and not vscode_app.stat.exists
      community.general.homebrew_cask:
        name: "{{ item }}"
      with_items:
        - visual-studio-code

    - name: "Install VSCode extensions"
      when: vscode|bool
      command: code --install-extension {{ item.id | default(item) }}
      with_items: "{{ vscode_extensions }}"
      register: vscode_result
      changed_when: "'already installed' not in vscode_result.stdout"

    - name: Check if Cursor is already installed
      when: cursor|bool
      ansible.builtin.stat:
        path: /Applications/Cursor.app
      register: cursor_app

    - name: Install Cursor
      when: cursor|bool and not cursor_app.stat.exists
      community.general.homebrew_cask:
        name: "{{ item }}"
      with_items:
        - cursor

    - name: Installing brew cask packages
      community.general.homebrew_cask:
        name: "{{ item }}"
        sudo_password: "{{ password }}"
      with_items:
        - drawio
        - android-file-transfer
        - ledger-live
        - utm
        - zulu@17

    - name: Check if Postman app already exists
      ansible.builtin.stat:
        path: /Applications/Postman.app
      register: postman_app

    - name: Installing Postman
      when: not postman_app.stat.exists
      community.general.homebrew_cask:
        name: postman

    - name: Check if Insomnia app already exists
      ansible.builtin.stat:
        path: /Applications/Insomnia.app
      register: insomnia_app

    - name: Installing Insomnia
      when: not insomnia_app.stat.exists
      community.general.homebrew_cask:
        name: insomnia
        sudo_password: "{{ password }}"

    - name: Installing brew packages
      community.general.homebrew:
        name: "{{ item }}"
      with_items:
        - rbenv
        - ruby-build
        - scrcpy
        - git-lfs
        - ios-deploy
        - wget
        - unzip
        - gzip
        - xz
        - openjdk@17

    - name: Installing Android Studio
      when: androidStudio|bool
      community.general.homebrew_cask:
        name: android-studio

    - name: Installing proto toolchain manager
      ansible.builtin.shell:
        cmd: curl -fsSL https://moonrepo.dev/install/proto.sh | bash

    - name: Installing default node/npm/pnpm versions
      ansible.builtin.shell:
        cmd: source ~/.zshrc && proto install {{ item.name }} {{ item.version }}
      with_items: "{{ proto_tools }}"

    - name: Installing specific ruby version
      ignore_errors: yes
      ansible.builtin.shell:
        cmd: rbenv install 3.3.0
      register: rbenv_result
      failed_when:
        - '"already exist" not in rbenv_result.stderr and rbenv_result.rc == 1'
        - rbenv_result.rc > 1
      changed_when: '"already exist" not in rbenv_result.stderr'

    - name: Specifying global ruby version
      ansible.builtin.shell:
        cmd: rbenv global 3.3.0

    - name: Installing bundler - consistent environment for Ruby projects
      ansible.builtin.shell:
        cmd: eval "$(rbenv init -)" && gem install bundler --version 2.3.10

    - name: Installing fastlane - tool to automate tedious tasks like releasing app for example
      ansible.builtin.shell:
        cmd: eval "$(rbenv init -)" && gem install fastlane --version 2.205.1

    - name: Installing Xcode plugin for kotlin
      ansible.builtin.shell:
        cmd: brew install xcode-kotlin

    - name: Installing xcode-kotlin
      ansible.builtin.shell:
        cmd: xcode-kotlin install
