# 
# This playbook installs tools a developer need to work on Ledger products
#

---
- hosts: localhost
  gather_facts: no
  connection: local

  vars:
    vscode_extensions:
      - { name: "Markdown Preview Enhanced", id: "shd101wyy.markdown-preview-enhanced" }
      - { name: "ESLint", id: "dbaeumer.vscode-eslint"}
      - { name: "Prettier - Code formatter", id: "esbenp.prettier-vscode"}
      - { name: "Live Share", id: "MS-vsliveshare.vsliveshare"}

  vars_prompt:
    - name: sublime
      prompt: "Install Sublime Text ?"
      default: "yes"
      private: no
    - name: vscode
      prompt: "Install VSCode ?"
      default: "yes"
      private: no

  tasks:
  - name: "Install Sublime Text"
    when: sublime|bool
    community.general.homebrew_cask:
      name: "{{ item }}"
    with_items:
      - sublime-merge
      - sublime-text
      - android-studio

  - name: "Install VSCode"
    when: vscode|bool
    community.general.homebrew_cask:
      name: "{{ item }}"
    with_items:
      - visual-studio-code
      
  - name: "Install VSCode extensions"
    when: vscode|bool
    command: code --install-extension {{ item.id | default(item) }}
    with_items: "{{ vscode_extensions }}"
    register: vscode_result
    changed_when: "'already installed' not in vscode_result.stdout"

  - name: Installing brew cask packages
    community.general.homebrew_cask:
      name: "{{ item }}"
    with_items:
      - postman
      - drawio
      - android-file-transfer
      - ledger-live
      - utm

  - name: Installing brew packages
    community.general.homebrew:
      name: "{{ item }}"
    with_items:
      - rbenv
      - ruby-build
      - nvm
      - scrcpy
      - git-lfs
      - pnpm
      - java11

  - name: Installing specific ruby version
    ignore_errors: yes
    ansible.builtin.shell:
      cmd: rbenv install 2.7.2

  - name: Specifying global ruby version
    ansible.builtin.shell:
      cmd: rbenv global 2.7.2

  - name: Installing bundler - consistent environment for Ruby projects
    ansible.builtin.shell:
      cmd: eval "$(rbenv init -)" && gem install bundler --version 2.3.10

  - name: Installing fastlane - tool to automate tedious tasks like releasing app for example
    ansible.builtin.shell:
      cmd: eval "$(rbenv init -)" && gem install fastlane --version 2.205.1

  - name: Install node 16.18.0 with nvm
    ansible.builtin.shell:
      cmd: source ~/.zshrc && nvm install 16.18.0
    args:
      executable: /bin/zsh

  - name: Setup JAVA HOME
    ansible.builtin.shell:
      cmd: zsh bin/setup_java_home.sh
    args:
      executable: /bin/zsh

  - name: Installing yarn
    community.general.npm:
      name: yarn
      global: true
... 
